spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/YarismaDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 80

